name: build containers and publish it to ghcr and dockerhub

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: 
          - name: omabuild
            context: containers/oma
            platforms: linux/amd64    #linux/arm64 take a long time for development
          - name: omadarwin
            context: containers/darwin
            platforms: linux/amd64,linux/arm64
          - name: omabuild-rdf-py
            context: containers/rdf/biosoda_py
            platforms: linux/amd64    #linux/arm64 take a long time for development
          - name: omabuild-rdf-java
            context: containers/rdf/biosoda_java
            platforms: linux/amd64,linux/arm64
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dessimozlab/${{ matrix.name }}
            ghcr.io/dessimozlab/${{ matrix.name }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=edge

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.name }} container
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "labgit=${{ secrets.LABGIT }}"

  run-nextflow:
    name: run nextflow pipeline with testdata
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: '24.10.5'

      - name: Run Nextflow pipeline
        run: nextflow run main.nf -profile docker,test