name: build container and publish them

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build darwin container
        uses: docker/build-push-action@v6
        with:
          context: containers/darwin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dessimozlab/omadarwin:nf-latest
          secrets: |
            "labgit=${{ secrets.LABGIT }}"

      - name: Build python oma build container
        uses: docker/build-push-action@v6
        with:
          context: containers/oma
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dessimozlab/omabuild:nf-latest
          secrets: |
            "labgit=${{ secrets.LABGIT }}"