name: Run Nextflow Pipeline

on:
  workflow_run:
    workflows:
        - build omabuild container and publish it to ghcr and dockerhub
        - build omadarwin container and publish it to ghcr and dockerhub
    types:
      - completed


jobs:

  run-nextflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          chmod +x nextflow
          mv nextflow /usr/local/bin/

      - name: Run Nextflow pipeline
        run: nextflow run main.nf -profile docker -params-file test-params.json